name: Apple-IOS_CI-CD_demo

on:
  push:
    branches:
      - master
      - staging
      - dev
  workflow_dispatch:

jobs:
  publish-ios-app:
    needs:
      - build-ios-app
    runs-on: macos-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@v2

      - name: Install FASTLANE
        run: |
          gem cleanup
          gem install fastlane

      - name: Publish to Dev
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: 'xpye-zgte-vutz-etxy'
        run: |
           fastlane pilot upload --username niket.kapadia@azilen.com --apple_id 1437397999  \
           -i AutoDeployDemo.ipa --itc_provider AzilenTechnologiesPvtLtd \ 
           --app_identifier com.azilen.iostest --team_id 1155485  \
           --changelog "$(cat release_note)"  --verbose
        working-directory: 'AutoDeployDemo-25/' 